### ISSUE TITLE
Separate frontend and backend

### ISSUE THREAD

**Issue by domenkozar** [madjar/howoldis#12]
@madjar would you accept a PR where backend does restful api (so it can be reused) and frontend is separated, for example written in a few lines of [Elm](elm-lang.org)?

**Comment by madjar** [comment]
I have nothing against it, but I feel it's overkill for such a thin layer on top of Hydra.

But feel free, I'll merge anything from you!

**Comment by domenkozar** [comment]
I agree it's an overkill, but I'd like to write an IRC bot that queries channel information and announces delays, and it would be best to just expose an api at howoldis for the use case. Maybe just needs another endpoint serving JSON for now.

**Comment by domenkozar** [comment]
I have a very basic `/api/channels` based on `DiffChannel` record at https://github.com/domenkozar/howoldis/commit/2e373d3eb6d0dacc839b64eb2430b4ae631c5cf2

But I'd like to:
- [x] include timediff as time of seconds 
- [x] include tests url
- [x] include link to the channel itself
- [x] include git commit
