### ISSUE TITLE
Properly handle CEST/CET 

### ISSUE THREAD

**Issue by domenkozar** [madjar/howoldis#13]
So currently the summer time is still hardcoded in howoldis.

I've looked into different libraries that we have to glue together here and the API is a terrible mess.

I think the solution would be to parse the time from nixos.org and figure out the timezone compared to UTC time.

Modules involved:
- https://hackage.haskell.org/package/time-1.6.0.1/docs/Data-Time-Clock.html
- https://hackage.haskell.org/package/time-1.6.0.1/docs/Data-Time-LocalTime.html
- https://hackage.haskell.org/package/time-1.6.0.1/docs/Data-Time-Format.html

Summer time ends on 30th October.

**Comment by madjar** [comment]
As was looking into thyme at some point (https://hackage.haskell.org/package/thyme-0.3.5.5). Would it be less of a mess?

**Comment by domenkozar** [comment]
It has very similar API, but it also has human diff, so that's good :)

We'll have to use `getTimeZone` from https://hackage.haskell.org/package/thyme-0.3.5.5/docs/Data-Thyme-LocalTime.html#g:2

**Comment by domenkozar** [comment]
I'll try to address this before CEST -> CET change on 30th October.

**Comment by domenkozar** [comment]
Using `time` and `tz` in ghci:

```
import Data.Time.LocalTime
import Data.Time.Format
import Data.Time.Zones
import Data.Time.Zones.All

x = parseTime defaultTimeLocale "%F %R" "2016-10-14 10:48"
let Just y = x
localTimeToUTCTZ (tzByLabel Europe__Rome) (y :: LocalTime)
```
