### ISSUE TITLE
Timezone issues?

### ISSUE THREAD

**Issue by domenkozar** [madjar/howoldis#2]
![2015-03-31-182720_1214x563_scrot](https://cloud.githubusercontent.com/assets/126339/6923693/9c53ea02-d7d3-11e4-9229-1db2ddd4c8cd.png)

**Comment by madjar** [comment]
I guess the dates on http://nixos.org/channels/ are not UTC :) Any idea which TZ it could be ?

**Comment by domenkozar** [comment]
Probably CET.

**Comment by madjar** [comment]
Fixed (though I'm pretty sure this will break for next DST)
