### ISSUE TITLE
CLI output only mode?

### ISSUE THREAD

**Issue by womfoo** [madjar/howoldis#4]
This can be useful for people who live in a terminal.

Is this something we can add?

**Comment by madjar** [comment]
It is possible, but since that would require me setting up some kind of distribution mechanism for it to be actually useful, I'm not really fond of the idea.

If you don't mind, I can propose you that ugly bash oneliner instead:

``` bash
$ curl -s https://nixos.org/channels/ | sed -n 's|.*href="\(.*\)/">.*align="right">\(.*\)  <.*|\1 \2|p'
nixos-13.10 19-Jul-2014 21:56
nixos-14.04-small 16-Feb-2015 18:52
nixos-14.04 25-Feb-2015 18:22
nixos-14.12-small 21-Dec-2015 11:01
nixos-14.12 27-Sep-2015 15:55
nixos-15.09-small 04-Jan-2016 14:25
nixos-15.09 14-Dec-2015 06:03
nixos-unstable-small 09-Dec-2015 16:55
nixos-unstable 11-Dec-2015 12:40
nixpkgs-unstable 31-Dec-2015 03:47
```

**Comment by womfoo** [comment]
Thanks! This one liner works for me.
